### ISSUE TITLE
compatibility with PHPUnit > 5

### ISSUE THREAD

**Issue by DanielBoettner** [estahn/phpunit-json-assertions#16]
I don't know if this repository is still maintained. 

If so, you may want to update for compatibility with PHPUnit _**^6**_

`\PHPUnit_Framework_Assert`

to 

` \PHPUnit\Framework\Assert`

**Comment by estahn** [comment]
@DanielBoettner It's still maintained. Would you like to give it a shot and create a pull request?

**Comment by DanielBoettner** [comment]
Sure, I'll try to schedule it ASAP.

**Comment by estahn** [comment]
see #15
