### ISSUE TITLE
Exception should be thrown when schema file is not found

### ISSUE THREAD

**Issue by smilesrg** [estahn/phpunit-json-assertions#18]
Currently, if schema file is not found, `Assert::assertJsonMatchesSchema()` throws an exception `JsonSchema\Exception\JsonDecodingException: Control character error, possibly incorrectly encoded`. I took hours when I tried to understand what's wrong with schema file I passed instead of being aware of actual error immediately.

**Comment by estahn** [comment]
@smilesrg Thanks. Would you mind providing a pull request with your suggested change?

**Comment by smilesrg** [comment]
@estahn as soon as I have free time :)

**Comment by smilesrg** [comment]
@estahn Oh, I see that you did it! Thank you )
